### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 4.722656GB memory on GPU 0, 6.407104GB memory has been allocated and available memory is only 4.354065GB

### ISSUE THREAD

**Issue by gaojing8500** [JiehangXie/PaddleBoBo#10]
一块2080ti的显卡12G 应该是不行的，因为需要同时加载两个预训练模型
![image](https://user-images.githubusercontent.com/20908110/148531649-3b8e61a2-1c52-4d89-87b3-9f20c1565b70.png)

**Comment by JiehangXie** [comment]
显存不足，建议在线运行。



发自我的iPhone


------------------ Original ------------------
From: gaojing8500 ***@***.***&gt;
Date: Fri,Jan 7,2022 6:36 PM
To: JiehangXie/PaddleBoBo ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [JiehangXie/PaddleBoBo] Out of memory error on GPU 0. Cannot allocate4.722656GB memory on GPU 0, 6.407104GB memory has been allocated and availablememory is only 4.354065GB (Issue #10)





 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gaojing8500** [comment]
![image](https://user-images.githubusercontent.com/20908110/148876662-923045ec-1b49-4e95-ba95-e18898b35367.png)
demo至少需要17G的显存
