### ISSUE TITLE
 Ubuntu 环境，运行快速开始时候，出现了一个错误

### ISSUE THREAD

**Issue by laoxiong** [JiehangXie/PaddleBoBo#11]
`
环境：Ubuntu 20.04  Python 3.8.10，前面安装等执行都正常
python3 general_demo.py --human ./file/input/test.mp4 --output output.mp4 --text 各位开发者大家好，欢迎使用飞桨。

Building prefix dict from the default dictionary ...
[2022-01-09 21:51:25] [DEBUG] [__init__.py:113] Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
[2022-01-09 21:51:25] [DEBUG] [__init__.py:132] Loading model from cache /tmp/jieba.cache
Loading model cost 0.539 seconds.
[2022-01-09 21:51:25] [DEBUG] [__init__.py:164] Loading model cost 0.539 seconds.
Prefix dict has been built successfully.
[2022-01-09 21:51:25] [DEBUG] [__init__.py:166] Prefix dict has been built successfully.
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/math_op_patch.py:251: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.int32, the right dtype will convert to paddle.int64
  warnings.warn(
Traceback (most recent call last):
  File "general_demo.py", line 18, in <module>
    video = wav2lip(args.human,wavfile,args.output) #将音频合成到唇形视频
  File "/root/PaddleBoBo/PaddleTools/GAN.py", line 11, in wav2lip
    wav2lip_predictor.run(input_video, input_audio, output)
  File "/usr/local/lib/python3.8/dist-packages/ppgan/apps/wav2lip_predictor.py", line 176, in run
    raise ValueError(
ValueError: --face argument must be a valid path to video/image file
`

**Comment by gaojing8500** [comment]
应该是路径不对吧

**Comment by JiehangXie** [comment]
先运行 `python create_virtual_human.py --config default.yaml` 再运行视频生成。

**Comment by laoxiong** [comment]
> 先运行 `python create_virtual_human.py --config default.yaml` 再运行视频生成。

这已经运行完了，没有错误抛出。这个运行会生成什么文件吗？

**Comment by JiehangXie** [comment]
会在input文件夹下面生成一个mp4文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: crazybear ***@***.***&gt;
发送时间: 2022年1月10日 19:29
收件人: JiehangXie/PaddleBoBo ***@***.***&gt;
抄送: JiehangXie ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[JiehangXie/PaddleBoBo]  Ubuntu 环境，运行快速开始时候，出现了一个错误 (Issue #11)





  
先运行 python create_virtual_human.py --config default.yaml 再运行视频生成。
  
这已经运行完了，没有错误抛出。这个运行会生成什么文件吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoxiong** [comment]
发现还是前面执行错误，被 killed 了。
python3  create_virtual_human.py --config default.yaml
`
/usr/local/lib/python3.8/dist-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_0. generator.noises.noise_0 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_1. generator.noises.noise_1 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_2. generator.noises.noise_2 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_3. generator.noises.noise_3 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_4. generator.noises.noise_4 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_5. generator.noises.noise_5 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_6. generator.noises.noise_6 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_7. generator.noises.noise_7 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_8. generator.noises.noise_8 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_9. generator.noises.noise_9 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_10. generator.noises.noise_10 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_11. generator.noises.noise_11 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_12. generator.noises.noise_12 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_13. generator.noises.noise_13 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py:1436: UserWarning: Skip loading for generator.noises.noise_14. generator.noises.noise_14 is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
[01/11 12:23:01] ppgan INFO: Found /root/.cache/ppgan/vox-cpk-512.pdparams
[01/11 12:23:04] ppgan INFO: Found /root/.cache/ppgan/GPEN-512.pdparams
Killed

`

**Comment by JiehangXie** [comment]
CPU环境吗？可能是配置不够导致进程死掉的

**Comment by laoxiong** [comment]
> 



> CPU环境吗？可能是配置不够导致进程死掉的

是的，CPU 环境

**Comment by JiehangXie** [comment]
建议你用飞桨AIStudio的在线运行环境吧，这个生成项目是需要比较高的硬件配置。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiehangXie/PaddleBoBo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiehangXie/PaddleBoBo]  Ubuntu 环境，运行快速开始时候，出现了一个错误 (Issue #11)





    
CPU环境吗？可能是配置不够导致进程死掉的
  
是的，CPU 环境
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by laoxiong** [comment]
多谢

> 建议你用飞桨AIStudio的在线运行环境吧，这个生成项目是需要比较高的硬件配置。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JiehangXie/PaddleBoBo" ***@***.***&gt;; 发送时间:&nbsp;2022年1月11日(星期二) 下午3:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [JiehangXie/PaddleBoBo] Ubuntu 环境，运行快速开始时候，出现了一个错误 (Issue #11) CPU环境吗？可能是配置不够导致进程死掉的 是的，CPU 环境 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;
