### ISSUE TITLE
gpen 模型是用哪个版本保存的，是不是有错误

### ISSUE THREAD

**Issue by ziyoujiyi** [JiehangXie/PaddleBoBo#12]
[01/10 10:12:33] ppgan INFO: Found /root/.cache/ppgan/GPEN-512.pdparams
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/framework/io.py", line 936, in load
    load_result = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated

**Comment by JiehangXie** [comment]
可以给更详细的报错信息吗？
最好能附上输入的图片格式和分辨率大小，谢谢

**Comment by ziyoujiyi** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/3280614?channelType=0&channel=0    按着教程来的，用的 paddlebobo develop 分支，执行 python create_virtual_human.py --config default.yaml 时报错，paddle版本 2.2.1 ，用的是官方镜像，cpu 版本
![image](https://user-images.githubusercontent.com/73728031/148867970-4e5d90ee-924c-4564-bcef-f64fdb9a5321.png)

**Comment by JiehangXie** [comment]
感觉是模型下载中断失败了，你尝试下删除/root/.cache/ppgan/GPEN-512.pdparams再运行程序重新下载试试？

**Comment by ziyoujiyi** [comment]
"No ffmpeg exe could be found. Install ffmpeg on your system, "    这个代码只能在windows上跑么，有没windows运行环境呀

**Comment by JiehangXie** [comment]
> "No ffmpeg exe could be found. Install ffmpeg on your system, " 这个代码只能在windows上跑么，有没windows运行环境呀

这个应该是ffmpeg没有被加进系统的环境变量，具体可参考
Win: https://www.jianshu.com/p/2b609afb9800
Linux: https://blog.csdn.net/qq_38631503/article/details/80007128
