### ISSUE TITLE
news_app.py有问题

### ISSUE THREAD

**Issue by dengmingD** [JiehangXie/PaddleBoBo#13]
51行：video = wav2lip(_Config.GAN()['FOM_OUTPUT_VIDEO'],wavfile,VIDEO_SAVE_PATH)
应改为
video = wav2lip(_Config.GAN()['FOM_DRIVING_VIDEO'],wavfile,VIDEO_SAVE_PATH)

**Comment by JiehangXie** [comment]
这个程序的原理是先用驱动视频做表情迁移到输入图片，然后再用新的视频推理，所以wav2lip部分应该是输入新生成的test.mp4
