### ISSUE TITLE
静态图片的要求

### ISSUE THREAD

**Issue by wanghaisheng** [JiehangXie/PaddleBoBo#17]
类似熊猫头这样的图片能不能用？

**Comment by JiehangXie** [comment]
这个没测试过，你可以试一下，但感觉黑白的嘴不太行

**Comment by wanghaisheng** [comment]
恩 谢谢 我机器配置好像跑不起来。
我再看看

**Comment by JiehangXie** [comment]
用aistudio的V100 32G环境吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanghaisheng ***@***.***&gt;
发送时间: 2022年3月4日 22:37
收件人: JiehangXie/PaddleBoBo ***@***.***&gt;
抄送: JiehangXie ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JiehangXie/PaddleBoBo] 静态图片的要求 (Issue #17)






恩 谢谢 我机器配置好像跑不起来。
我再看看

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
