### ISSUE TITLE
使用play.py播放本地非生成的视频文件，会有音频和视频不同步问题

### ISSUE THREAD

**Issue by wduo** [JiehangXie/PaddleBoBo#18]
如题，
我用电脑自带播放器播放从网站上下载的视频时，视频本身的音频和视频的正常同步的，口型也和音频能对上。
用play.py播放时，视频要比音频快一些。请问是否是哪里需要调整呢，应该如何解决呢？
期待您的回复，谢谢！@JiehangXie

**Comment by JiehangXie** [comment]
这个其实是python opencv读取帧画音不同步导致的，现在还没有更好的解决方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiehangXie/PaddleBoBo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[JiehangXie/PaddleBoBo] 使用play.py播放本地非生成的视频文件，会有音频和视频不同步问题 (Issue #18)





 
如题，
 我用电脑自带播放器播放从网站上下载的视频时，视频本身的音频和视频的正常同步的，口型也和音频能对上。
 用play.py播放时，视频要比音频快一些。请问是否是哪里需要调整呢，应该如何解决呢？
 ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
