### ISSUE TITLE
我有4个 Tesla M60 也显存不足，为什么能用到了一个

### ISSUE THREAD

**Issue by 19920716** [JiehangXie/PaddleBoBo#20]
Out of memory error on GPU 0. Cannot allocate 4.722656GB memory on GPU 0, 6.399963GB memory has been allocated and available memory is only 1.039795GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
. (at ..\paddle\fluid\imperative\tracer.cc:221)
![image](https://user-images.githubusercontent.com/19903385/159723516-4170f83b-0ece-4597-a3fe-a0a5791b8202.png)

**Comment by JiehangXie** [comment]
python的机制问题，单线程就算多个显卡也只会用到其中一个显卡，可以参考这个PR先降低一下batchsize减少显存占用https://github.com/JiehangXie/PaddleBoBo/pull/19
