### ISSUE TITLE
声音如何切换男女？

### ISSUE THREAD

**Issue by yangboz** [JiehangXie/PaddleBoBo#29]
只看到这些选项

TTS:
  SPEED: 1.0
  PITCH: 1.0
  ENERGY: 1.0

如题 。

**Comment by JiehangXie** [comment]
目前还没有男声的模型，如果有男声的数据集，可以参考下这个项目进行训练然后更换tts里面的模型文件即可。
https://github.com/PaddlePaddle/PaddleSpeech

**Comment by qiqilie** [comment]
请问如何

> 目前还没有男声的模型，如果有男声的数据集，可以参考下这个项目进行训练然后更换tts里面的模型文件即可。 https://github.com/PaddlePaddle/PaddleSpeech

请问具体替换TTS里面的哪个位置，有代码示例吗？
