### ISSUE TITLE
cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils'

### ISSUE THREAD

**Issue by WestbrookZero** [JiehangXie/PaddleBoBo#39]
运行general_demo.py报错如下：
D:\InstallPath\Develop\Anaconda3\2020.07\envs\PaddleBoBo_Py3.7\python.exe G:/Project/AIBroadcast/PaddleBoBo/general_demo.py
Traceback (most recent call last):
  File "G:/Project/AIBroadcast/PaddleBoBo/general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "G:\Project\AIBroadcast\PaddleBoBo\PaddleTools\TTS.py", line 11, in <module>
    from paddlespeech.cli.utils import MODEL_HOME
ImportError: cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (D:\InstallPath\Develop\Anaconda3\2020.07\envs\PaddleBoBo_Py3.7\lib\site-packages\paddlespeech\cli\utils.py)

**Comment by JiehangXie** [comment]
这个问题是由于paddlespeech的更新引起的，预计这周末会修复这个问题
如您急需，可以直接用paddlespeech官方最新版本的包替换TTS部分即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiehangXie/PaddleBoBo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 中午1:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JiehangXie/PaddleBoBo] cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (Issue #39)





 
运行general_demo.py报错如下：
 D:\InstallPath\Develop\Anaconda3\2020.07\envs\PaddleBoBo_Py3.7\python.exe G:/Project/AIBroadcast/PaddleBoBo/general_demo.py
 Traceback (most recent call last):
 File "G:/Project/AIBroadcast/PaddleBoBo/general_demo.py", line 6, in 
 from PaddleTools.TTS import TTSExecutor
 File "G:\Project\AIBroadcast\PaddleBoBo\PaddleTools\TTS.py", line 11, in 
 from paddlespeech.cli.utils import MODEL_HOME
 ImportError: cannot import name 'MODEL_HOME' from 'paddlespeech.cli.utils' (D:\InstallPath\Develop\Anaconda3\2020.07\envs\PaddleBoBo_Py3.7\lib\site-packages\paddlespeech\cli\utils.py)

**Comment by WestbrookZero** [comment]
> 直接用paddlespeech官方最新版本的包替换TTS部分即可。

那我用之前的paddlespeech版本就不会报这个错了么？还有就是这句没太明白，应该怎么操作？

**Comment by ladenol** [comment]
> > 直接用paddlespeech官方最新版本的包替换TTS部分即可。
> 
> 那我用之前的paddlespeech版本就不会报这个错了么？还有就是这句没太明白，应该怎么操作？

pip install  paddlespeech==1.0.0 -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

安装低版本paddlespeech

**Comment by WestbrookZero** [comment]
> > > 直接用paddlespeech官方最新版本的包替换TTS部分即可。
> > 
> > 
> > 那我用之前的paddlespeech版本就不会报这个错了么？还有就是这句没太明白，应该怎么操作？
> 
> pip install paddlespeech==1.0.0 -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
> 
> 安装低版本paddlespeech

已解决，谢谢！

**Comment by mlb0925** [comment]
也遇到这个问题了 这样就解决了
```
from paddlespeech.utils.env import MODEL_HOME
```

**Comment by BeeFl** [comment]
> 也遇到这个问题了 这样就解决了
> 
> ```
> from paddlespeech.utils.env import MODEL_HOME
> ```

我按照这个方法解决了这个问题
