### ISSUE TITLE
博主，报错了~请看下

### ISSUE THREAD

**Issue by zlszhonglongshen** [JiehangXie/PaddleBoBo#4]
Traceback (most recent call last):
  File "news_app.py", line 35, in <module>
    TTS = TTSExecutor()
TypeError: __init__() missing 1 required positional argument: 'config'

**Comment by JiehangXie** [comment]
谢谢反馈，已修复，欢迎使用~
https://github.com/JiehangXie/PaddleBoBo/commit/e1f890cd3d6134e7a2aa461986936cbea3953890

**Comment by JiehangXie** [comment]
使用新闻直播可能需要更新一下cookie

**Comment by zlszhonglongshen** [comment]
> 使用新闻直播可能需要更新一下cookie

![image](https://user-images.githubusercontent.com/9023908/147842993-4245db76-c72e-476c-bedb-2a3740456fb6.png)
大佬帮忙看看，可以拿到新闻信息，但是会报错。

**Comment by JiehangXie** [comment]
> > 使用新闻直播可能需要更新一下cookie
> 
> ![image](https://user-images.githubusercontent.com/9023908/147842993-4245db76-c72e-476c-bedb-2a3740456fb6.png) 大佬帮忙看看，可以拿到新闻信息，但是会报错。

在运行news_app.py之前需要先运行一下create_virtual_human.py创建动态虚拟人物，这一步忘记在文本中说明了，抱歉！我晚些会加上说明。

**Comment by chsyts** [comment]
> 使用新闻直播可能需要更新一下cookie

博主，这个cookie是同花顺的吗，我感觉cookie格式和代码中的不一样

**Comment by JiehangXie** [comment]
> > 使用新闻直播可能需要更新一下cookie
> 
> 博主，这个cookie是同花顺的吗，我感觉cookie格式和代码中的不一样

https://news.10jqka.com.cn/realtimenews.html 在这个页面获取最新的cookie

**Comment by chsyts** [comment]
> e

谢谢哈
