### ISSUE TITLE
请问怎么生成男声

### ISSUE THREAD

**Issue by haibaobaby** [JiehangXie/PaddleBoBo#5]
请问怎么生成男声，现在都是女声。

**Comment by JiehangXie** [comment]
抱歉，目前还没有男声模型，如果你有急需求可以使用[PaddleSpeech](https://github.com/PaddlePaddle/PaddleSpeech)训练一个的，谢谢使用。

**Comment by haibaobaby** [comment]
您好，您的邮件已收到，我会尽快回复！
