### ISSUE TITLE
关于GPU内存问题

### ISSUE THREAD

**Issue by congling** [JiehangXie/PaddleBoBo#6]
#python general_demo.py --human ./file/input/test.mp4 --output ../output.mp4 --text 各位开发者大家好，我是您的专属虚拟主播，很高兴能为您服务。

结果告诉我内存不足，Out of memory error on GPU 0. Cannot allocate 4.722656GB memory on GPU 0, 13.023560GB memory has been allocated and available memory is only 2.975952GB.

我的机器是3080，16G显存，不管这句话多长都是分配这么多内存，配置建议多少啊？

**Comment by JiehangXie** [comment]
嗯嗯，谢谢反馈，我刚测试了一下，这一步使用GPU的话，GPU显存占用大概是17-18G左右，16G刚好卡门槛上了，建议你使用AIStudio TeslaV100 32G在线运行吧，https://aistudio.baidu.com/aistudio/projectdetail/3280614?contributionType=1&shared=1

**Comment by ZeeLyn** [comment]
3080都跑不动，这门槛有点高啊，哈哈哈

**Comment by JiehangXie** [comment]
是的，真心建议你在飞桨AIStudio用免费的Tesla V100 32G算力跑！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiehangXie/PaddleBoBo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiehangXie/PaddleBoBo] 关于GPU内存问题 (Issue #6)





 
3080都跑不动，这门槛有点高啊，哈哈哈
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by congling** [comment]
谢谢！
