### ISSUE TITLE
请问 OSError: sndfile library not found 该如何处理（librosa 和 libsndfile 都已安装）

### ISSUE THREAD

**Issue by ArcherShirou** [JiehangXie/PaddleBoBo#8]

**Comment by JiehangXie** [comment]
是在pip install ppgan paddlespeech的时候出现的报错吗？可否提供更详细的traceback信息？

**Comment by ArcherShirou** [comment]
您好，这是报错信息，是在运行general_demo时报的错：
Traceback (most recent call last):
  File "/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ash/my_project/PaddleBoBo/general_demo.py", line 6, in <module>
    from PaddleTools.TTS import TTSExecutor
  File "/Users/ash/my_project/PaddleBoBo/PaddleTools/TTS.py", line 6, in <module>
    import soundfile as sf
  File "/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib': dlopen(/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib' (no such file), '/usr/local/lib/libsndfile.dylib' (no such file), '/usr/lib/libsndfile.dylib' (no such file)

**Comment by JiehangXie** [comment]
> 您好，这是报错信息，是在运行general_demo时报的错： Traceback (most recent call last): File "/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/soundfile.py", line 142, in raise OSError('sndfile library not found') OSError: sndfile library not found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/ash/my_project/PaddleBoBo/general_demo.py", line 6, in from PaddleTools.TTS import TTSExecutor File "/Users/ash/my_project/PaddleBoBo/PaddleTools/TTS.py", line 6, in import soundfile as sf File "/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/soundfile.py", line 162, in _snd = _ffi.dlopen(_os.path.join( OSError: cannot load library '/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib': dlopen(/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/ash/my_project/venv/lib/python3.8/site-packages/SoundFile-0.10.3.post1-py3.8.egg/_soundfile_data/libsndfile.dylib' (no such file), '/usr/local/lib/libsndfile.dylib' (no such file), '/usr/lib/libsndfile.dylib' (no such file)

你试试这个方法？https://blog.csdn.net/xddwz/article/details/109206548

**Comment by ArcherShirou** [comment]
您好，已试过，ppgan 不兼容librosa==0.6.0和numba==0.48.0 ，会报错

**Comment by JiehangXie** [comment]
> 您好，已试过，ppgan 不兼容librosa==0.6.0和numba==0.48.0 ，会报错

如果你是要用本地环境的话，建议你使用anaconda环境跑吧，原生python好像是会存在一些问题

**Comment by ArcherShirou** [comment]
好的，非常感谢
